# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
  Quotes: quotes/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
#- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  I am an atheist, a thinker, a problem sniffer, a music nerd, a free software advocate, a bathroom singer, a photographer, a chess player, an  idiot, and alive.

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-87967706-1
favicon: /favicon.ico
twitter_id: _sahilahuja
google_plus: https://plus.google.com/u/0/+SahilAhujaGoogle
fb_admins:
fb_app_id:
